//
// This is the grammar specification from the Final Draft of the generic spec.
//
////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007 IBM Corporation.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
//
//Contributors:
//    Philippe Charles (pcharles@us.ibm.com) - initial API and implementation

////////////////////////////////////////////////////////////////////////////////

package org.eclipse.imp.java.formatting.parser;

public interface JavaParsersym {
    public final static int
      TK_PackageDeclarationMarker = 113,
      TK_ImportDeclarationsMarker = 114,
      TK_ImportDeclarationMarker = 115,
      TK_TypeDeclarationMarker = 116,
      TK_ClassBodyDeclarationMarker = 117,
      TK_BlockStatementsMarker = 118,
      TK_TypeNameMarker = 119,
      TK_PackageNameMarker = 120,
      TK_ArgumentListMarker = 121,
      TK_StatementMarker = 122,
      TK_ExpressionMarker = 123,
      TK_MethodInvocationMarker = 124,
      TK_IntegerLiteral = 30,
      TK_LongLiteral = 31,
      TK_FloatingPointLiteral = 32,
      TK_DoubleLiteral = 33,
      TK_CharacterLiteral = 34,
      TK_StringLiteral = 35,
      TK_MINUS_MINUS = 28,
      TK_OR = 94,
      TK_MINUS = 49,
      TK_MINUS_EQUAL = 80,
      TK_NOT = 51,
      TK_NOT_EQUAL = 95,
      TK_REMAINDER = 96,
      TK_REMAINDER_EQUAL = 81,
      TK_AND = 74,
      TK_AND_AND = 97,
      TK_AND_EQUAL = 82,
      TK_LPAREN = 4,
      TK_RPAREN = 23,
      TK_MULTIPLY = 75,
      TK_MULTIPLY_EQUAL = 83,
      TK_COMMA = 45,
      TK_DOT = 43,
      TK_DIVIDE = 98,
      TK_DIVIDE_EQUAL = 84,
      TK_COLON = 54,
      TK_SEMICOLON = 14,
      TK_QUESTION = 99,
      TK_AT = 1,
      TK_LBRACKET = 40,
      TK_RBRACKET = 56,
      TK_XOR = 100,
      TK_XOR_EQUAL = 85,
      TK_LBRACE = 41,
      TK_OR_OR = 105,
      TK_OR_EQUAL = 86,
      TK_RBRACE = 46,
      TK_TWIDDLE = 52,
      TK_PLUS = 50,
      TK_PLUS_PLUS = 29,
      TK_PLUS_EQUAL = 87,
      TK_LESS = 42,
      TK_LEFT_SHIFT = 76,
      TK_LEFT_SHIFT_EQUAL = 88,
      TK_LESS_EQUAL = 89,
      TK_EQUAL = 55,
      TK_EQUAL_EQUAL = 101,
      TK_GREATER = 48,
      TK_GREATER_EQUAL = 128,
      TK_RIGHT_SHIFT = 129,
      TK_RIGHT_SHIFT_EQUAL = 130,
      TK_UNSIGNED_RIGHT_SHIFT = 131,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 132,
      TK_ELLIPSIS = 106,
      TK_BeginAction = 133,
      TK_EndAction = 134,
      TK_BeginJava = 135,
      TK_EndJava = 136,
      TK_NoAction = 137,
      TK_NullAction = 138,
      TK_BadAction = 139,
      TK_abstract = 19,
      TK_assert = 60,
      TK_boolean = 6,
      TK_break = 61,
      TK_byte = 7,
      TK_case = 77,
      TK_catch = 107,
      TK_char = 8,
      TK_class = 44,
      TK_const = 140,
      TK_continue = 62,
      TK_default = 72,
      TK_do = 63,
      TK_double = 9,
      TK_enum = 47,
      TK_else = 102,
      TK_extends = 90,
      TK_false = 36,
      TK_final = 21,
      TK_finally = 108,
      TK_float = 10,
      TK_for = 64,
      TK_goto = 141,
      TK_if = 65,
      TK_implements = 125,
      TK_import = 78,
      TK_instanceof = 91,
      TK_int = 11,
      TK_interface = 25,
      TK_long = 12,
      TK_native = 92,
      TK_new = 26,
      TK_null = 37,
      TK_package = 109,
      TK_private = 16,
      TK_protected = 17,
      TK_public = 15,
      TK_return = 66,
      TK_short = 13,
      TK_static = 18,
      TK_strictfp = 20,
      TK_super = 24,
      TK_switch = 67,
      TK_synchronized = 53,
      TK_this = 27,
      TK_throw = 68,
      TK_throws = 110,
      TK_transient = 57,
      TK_true = 38,
      TK_try = 69,
      TK_void = 22,
      TK_volatile = 58,
      TK_while = 59,
      TK_EOF_TOKEN = 73,
      TK_IDENTIFIER = 2,
      TK_VAR_Statement = 70,
      TK_VAR_BlockStatements = 93,
      TK_VAR_Expression = 71,
      TK_VAR_TypeDeclaration = 103,
      TK_VAR_ImportDeclarations = 111,
      TK_VAR_ImportDeclaration = 79,
      TK_VAR_ClassBodyDeclaration = 104,
      TK_VAR_PackageName = 126,
      TK_VAR_TypeName = 5,
      TK_VAR_MethodName = 39,
      TK_VAR_ArgumentListopt = 127,
      TK_VAR_ArgumentList = 112,
      TK_VAR_IDENTIFIER = 3,
      TK_ERROR_TOKEN = 142;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "AT",
                 "IDENTIFIER",
                 "VAR_IDENTIFIER",
                 "LPAREN",
                 "VAR_TypeName",
                 "boolean",
                 "byte",
                 "char",
                 "double",
                 "float",
                 "int",
                 "long",
                 "short",
                 "SEMICOLON",
                 "public",
                 "private",
                 "protected",
                 "static",
                 "abstract",
                 "strictfp",
                 "final",
                 "void",
                 "RPAREN",
                 "super",
                 "interface",
                 "new",
                 "this",
                 "MINUS_MINUS",
                 "PLUS_PLUS",
                 "IntegerLiteral",
                 "LongLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "false",
                 "null",
                 "true",
                 "VAR_MethodName",
                 "LBRACKET",
                 "LBRACE",
                 "LESS",
                 "DOT",
                 "class",
                 "COMMA",
                 "RBRACE",
                 "enum",
                 "GREATER",
                 "MINUS",
                 "PLUS",
                 "NOT",
                 "TWIDDLE",
                 "synchronized",
                 "COLON",
                 "EQUAL",
                 "RBRACKET",
                 "transient",
                 "volatile",
                 "while",
                 "assert",
                 "break",
                 "continue",
                 "do",
                 "for",
                 "if",
                 "return",
                 "switch",
                 "throw",
                 "try",
                 "VAR_Statement",
                 "VAR_Expression",
                 "default",
                 "EOF_TOKEN",
                 "AND",
                 "MULTIPLY",
                 "LEFT_SHIFT",
                 "case",
                 "import",
                 "VAR_ImportDeclaration",
                 "MINUS_EQUAL",
                 "REMAINDER_EQUAL",
                 "AND_EQUAL",
                 "MULTIPLY_EQUAL",
                 "DIVIDE_EQUAL",
                 "XOR_EQUAL",
                 "OR_EQUAL",
                 "PLUS_EQUAL",
                 "LEFT_SHIFT_EQUAL",
                 "LESS_EQUAL",
                 "extends",
                 "instanceof",
                 "native",
                 "VAR_BlockStatements",
                 "OR",
                 "NOT_EQUAL",
                 "REMAINDER",
                 "AND_AND",
                 "DIVIDE",
                 "QUESTION",
                 "XOR",
                 "EQUAL_EQUAL",
                 "else",
                 "VAR_TypeDeclaration",
                 "VAR_ClassBodyDeclaration",
                 "OR_OR",
                 "ELLIPSIS",
                 "catch",
                 "finally",
                 "package",
                 "throws",
                 "VAR_ImportDeclarations",
                 "VAR_ArgumentList",
                 "PackageDeclarationMarker",
                 "ImportDeclarationsMarker",
                 "ImportDeclarationMarker",
                 "TypeDeclarationMarker",
                 "ClassBodyDeclarationMarker",
                 "BlockStatementsMarker",
                 "TypeNameMarker",
                 "PackageNameMarker",
                 "ArgumentListMarker",
                 "StatementMarker",
                 "ExpressionMarker",
                 "MethodInvocationMarker",
                 "implements",
                 "VAR_PackageName",
                 "VAR_ArgumentListopt",
                 "GREATER_EQUAL",
                 "RIGHT_SHIFT",
                 "RIGHT_SHIFT_EQUAL",
                 "UNSIGNED_RIGHT_SHIFT",
                 "UNSIGNED_RIGHT_SHIFT_EQUAL",
                 "BeginAction",
                 "EndAction",
                 "BeginJava",
                 "EndJava",
                 "NoAction",
                 "NullAction",
                 "BadAction",
                 "const",
                 "goto",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
