/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerLowerCaseMapF.gi:1:1:1:10:1:10: Warning: The use of the escaped symbol "$Include" as a keyword has been deprecated. The proper spelling is %Include
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.java.core/src/org/eclipse/imp/java/parser/JavaKWLexer.gi:12:1:12:7:184:190: Warning: The use of the escaped symbol "$Export" as a keyword has been deprecated. The proper spelling is %Export
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.java.core/src/org/eclipse/imp/java/parser/JavaKWLexer.gi:64:1:64:4:739:742: Warning: The use of the escaped symbol "$End" as a keyword has been deprecated. The proper spelling is %End
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.java.core/src/org/eclipse/imp/java/parser/JavaKWLexer.gi:66:1:66:10:745:754: Warning: The use of the escaped symbol "$Terminals" as a keyword has been deprecated. The proper spelling is %Terminals
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.java.core/src/org/eclipse/imp/java/parser/JavaKWLexer.gi:69:1:69:4:888:891: Warning: The use of the escaped symbol "$End" as a keyword has been deprecated. The proper spelling is %End
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.java.core/src/org/eclipse/imp/java/parser/JavaKWLexer.gi:71:1:71:6:894:899: Warning: The use of the escaped symbol "$Start" as a keyword has been deprecated. The proper spelling is %Start
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.java.core/src/org/eclipse/imp/java/parser/JavaKWLexer.gi:73:1:73:4:913:916: Warning: The use of the escaped symbol "$End" as a keyword has been deprecated. The proper spelling is %End
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.java.core/src/org/eclipse/imp/java/parser/JavaKWLexer.gi:83:1:83:6:1022:1027: Warning: The use of the escaped symbol "$Rules" as a keyword has been deprecated. The proper spelling is %Rules
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.java.core/src/org/eclipse/imp/java/parser/JavaKWLexer.gi:391:1:391:4:7052:7055: Warning: The use of the escaped symbol "$End" as a keyword has been deprecated. The proper spelling is %End
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerLowerCaseMapF.gi:15:24:15:24:321:321: Warning: The macro "$" is undefined. No substitution made
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerLowerCaseMapF.gi:2:5:2:14:16:25: Informative: The terminal DollarSign is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerLowerCaseMapF.gi:3:5:3:11:39:45: Informative: The terminal Percent is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerLowerCaseMapF.gi:4:5:4:5:59:59: Informative: The terminal _ is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerLowerCaseMapF.gi:6:50:6:50:115:115: Informative: The terminal j is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerLowerCaseMapF.gi:7:20:7:20:151:151: Informative: The terminal q is useless.


