
// (C) Copyright IBM Corporation 2007
// 
// This file is part of the Eclipse IMP.

package org.eclipse.imp.java.parser;

public interface JavaParsersym {
    public final static int
      TK_PLUSPLUS = 14,
      TK_MINUSMINUS = 15,
      TK_EQEQ = 91,
      TK_LTEQ = 81,
      TK_GTEQ = 82,
      TK_NOTEQ = 92,
      TK_LSHIFT = 63,
      TK_RSHIFT = 64,
      TK_URSHIFT = 65,
      TK_PLUSEQ = 67,
      TK_MINUSEQ = 68,
      TK_MULTEQ = 69,
      TK_DIVEQ = 70,
      TK_ANDEQ = 71,
      TK_OREQ = 72,
      TK_XOREQ = 73,
      TK_MODEQ = 74,
      TK_LSHIFTEQ = 75,
      TK_RSHIFTEQ = 76,
      TK_URSHIFTEQ = 77,
      TK_OROR = 101,
      TK_ANDAND = 93,
      TK_PLUS = 45,
      TK_MINUS = 46,
      TK_NOT = 58,
      TK_MOD = 83,
      TK_XOR = 94,
      TK_AND = 95,
      TK_MULT = 78,
      TK_OR = 96,
      TK_COMP = 59,
      TK_DIV = 84,
      TK_GT = 85,
      TK_LT = 86,
      TK_LPAREN = 1,
      TK_RPAREN = 4,
      TK_LBRACE = 13,
      TK_RBRACE = 20,
      TK_LBRACK = 30,
      TK_RBRACK = 61,
      TK_SEMICOLON = 3,
      TK_QUESTION = 102,
      TK_COLON = 62,
      TK_COMMA = 44,
      TK_DOT = 32,
      TK_EQ = 66,
      TK_ABSTRACT = 35,
      TK_BOOLEAN = 5,
      TK_BREAK = 48,
      TK_BYTE = 6,
      TK_CASE = 79,
      TK_CATCH = 97,
      TK_CHAR = 7,
      TK_CLASS = 60,
      TK_CONST = 108,
      TK_CONTINUE = 49,
      TK_DEFAULT = 80,
      TK_DO = 50,
      TK_DOUBLE = 8,
      TK_ELSE = 87,
      TK_EXTENDS = 98,
      TK_FALSE = 21,
      TK_FINAL = 31,
      TK_FINALLY = 99,
      TK_FLOAT = 9,
      TK_FOR = 51,
      TK_GOTO = 109,
      TK_IF = 52,
      TK_IMPLEMENTS = 103,
      TK_IMPORT = 100,
      TK_INSTANCEOF = 88,
      TK_INT = 10,
      TK_INTERFACE = 89,
      TK_LONG = 11,
      TK_NATIVE = 36,
      TK_NEW = 16,
      TK_NULL = 22,
      TK_PACKAGE = 104,
      TK_PRIVATE = 37,
      TK_PROTECTED = 38,
      TK_PUBLIC = 39,
      TK_RETURN = 53,
      TK_SHORT = 12,
      TK_STATIC = 40,
      TK_STRICTFP = 41,
      TK_SUPER = 17,
      TK_SWITCH = 54,
      TK_SYNCHRONIZED = 33,
      TK_THIS = 18,
      TK_THROW = 55,
      TK_THROWS = 105,
      TK_TRANSIENT = 42,
      TK_TRUE = 23,
      TK_TRY = 56,
      TK_VOID = 19,
      TK_VOLATILE = 43,
      TK_WHILE = 47,
      TK_EOF_TOKEN = 90,
      TK_SlComment = 110,
      TK_MlComment = 111,
      TK_DocComment = 112,
      TK_IDENTIFIER = 2,
      TK_INTEGER_LITERAL = 24,
      TK_LONG_LITERAL = 25,
      TK_DOUBLE_LITERAL = 26,
      TK_FLOAT_LITERAL = 27,
      TK_CHARACTER_LITERAL = 28,
      TK_STRING_LITERAL = 29,
      TK_INTEGER_LITERAL_BD = 106,
      TK_LONG_LITERAL_BD = 107,
      TK_error = 34,
      TK_ASSERT = 57,
      TK_ERROR_TOKEN = 113;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "IDENTIFIER",
                 "SEMICOLON",
                 "RPAREN",
                 "BOOLEAN",
                 "BYTE",
                 "CHAR",
                 "DOUBLE",
                 "FLOAT",
                 "INT",
                 "LONG",
                 "SHORT",
                 "LBRACE",
                 "PLUSPLUS",
                 "MINUSMINUS",
                 "NEW",
                 "SUPER",
                 "THIS",
                 "VOID",
                 "RBRACE",
                 "FALSE",
                 "NULL",
                 "TRUE",
                 "INTEGER_LITERAL",
                 "LONG_LITERAL",
                 "DOUBLE_LITERAL",
                 "FLOAT_LITERAL",
                 "CHARACTER_LITERAL",
                 "STRING_LITERAL",
                 "LBRACK",
                 "FINAL",
                 "DOT",
                 "SYNCHRONIZED",
                 "error",
                 "ABSTRACT",
                 "NATIVE",
                 "PRIVATE",
                 "PROTECTED",
                 "PUBLIC",
                 "STATIC",
                 "STRICTFP",
                 "TRANSIENT",
                 "VOLATILE",
                 "COMMA",
                 "PLUS",
                 "MINUS",
                 "WHILE",
                 "BREAK",
                 "CONTINUE",
                 "DO",
                 "FOR",
                 "IF",
                 "RETURN",
                 "SWITCH",
                 "THROW",
                 "TRY",
                 "ASSERT",
                 "NOT",
                 "COMP",
                 "CLASS",
                 "RBRACK",
                 "COLON",
                 "LSHIFT",
                 "RSHIFT",
                 "URSHIFT",
                 "EQ",
                 "PLUSEQ",
                 "MINUSEQ",
                 "MULTEQ",
                 "DIVEQ",
                 "ANDEQ",
                 "OREQ",
                 "XOREQ",
                 "MODEQ",
                 "LSHIFTEQ",
                 "RSHIFTEQ",
                 "URSHIFTEQ",
                 "MULT",
                 "CASE",
                 "DEFAULT",
                 "LTEQ",
                 "GTEQ",
                 "MOD",
                 "DIV",
                 "GT",
                 "LT",
                 "ELSE",
                 "INSTANCEOF",
                 "INTERFACE",
                 "EOF_TOKEN",
                 "EQEQ",
                 "NOTEQ",
                 "ANDAND",
                 "XOR",
                 "AND",
                 "OR",
                 "CATCH",
                 "EXTENDS",
                 "FINALLY",
                 "IMPORT",
                 "OROR",
                 "QUESTION",
                 "IMPLEMENTS",
                 "PACKAGE",
                 "THROWS",
                 "INTEGER_LITERAL_BD",
                 "LONG_LITERAL_BD",
                 "CONST",
                 "GOTO",
                 "SlComment",
                 "MlComment",
                 "DocComment",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
